import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>NFT BUILD 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="font-bold text-[50px] text-gray-900 text-center mt-7">
        Hello World!
      </h1>
    </>
  );
}
